export const WORDS = [
  "apple",
  "banana",
  "cherry",
  "dragon",
  "elephant",
  "frost",
  "giraffe",
  "horizon",
  "igloo",
  "jungle",
  "kiwi",
  "lemon",
  "mystery",
  "noodle",
  "octopus",
  "puzzle",
  "quasar",
  "rainbow",
  "sunflower",
  "turtle",
  "unicorn",
  "vortex",
  "whisper",
  "xylophone",
  "yacht",
  "zebra",
  "avocado",
  "biscuit",
  "cactus",
  "dolphin",
  "firefly",
  "galaxy",
  "harmony",
  "iceberg",
  "jackal",
  "kiwifruit",
  "marsh",
  "nectar",
  "ocean",
  "peacock",
  "quilt",
  "sapphire",
  "tornado",
  "umbrella",
  "violet",
  "walrus",
  "cinnamon",
  "dandelion",
  "emerald",
  "flamingo",
  "gardenia",
  "honeydew",
  "inkling",
  "koala",
  "lavender",
  "mosaic",
  "ninja",
  "opal",
  "pebble",
  "quokka",
  "raspberry",
  "snowflake",
  "teacup",
  "ukulele",
  "vanilla",
  "whistle",
  "yarn",
  "zucchini",
  "beetle",
  "cylinder",
  "dolphin",
  "fireball",
  "giraffe",
  "hedgehog",
  "jovial",
  "kettle",
  "lemonade",
  "marigold",
  "nectarine",
  "octagonal",
  "piranha",
  "quokka",
  "rocket",
  "starfish",
  "telescope",
  "umbrella",
  "violet",
  "wombat",
  "xenon",
  "yonder",
];

export const LANGUAGES = {
	en: {
		src: "images/uk.svg",
		start: "Start game",
		logo: "[ HANGMAN GAME ]",
		confirm: "Are you sure you want to quit and lose your progress",
		tries: "TRIES LEFT: ",
		quit: "Quit",
		alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
		mode: "Dark mode",
		again: "Play again",
	},
	ru: {
		src: "images/ru.svg",
		start: "Начать игру",
		logo: "[ ВИСЕЛИЦА ]",
		confirm: "Вы уверены, что хотите закончить игру и потерять прогресс?",
		tries: "ОСТАЛОСЬ ПОПЫТОК: ",
		quit: "Выйти",
		alphabet: "АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ",
		mode: "Тёмная тема",
		again: "Играть снова",
	},
	it: {
		src: "images/it.svg",
		start: "Avvia il gioco",
		logo: "[ GIOCO DELL'IMPICCATO ]",
		confirm: "Sei sicuro di voler uscire e perdere i tuoi progressi?",
		tries: "TENTATIVI RIMASTI: ",
		quit: "Esci",
		alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
		mode: "Modalità scura",
		again: "Gioca di nuovo",
	},
}

export const KEYBOARD_LETTERS = Array.from(LANGUAGES.ru.alphabet);