const enWords = [
  "apple",
  "banana",
  "cherry",
  "dragon",
  "elephant",
  "frost",
  "giraffe",
  "horizon",
  "igloo",
  "jungle",
  "kiwi",
  "lemon",
  "mystery",
  "noodle",
  "octopus",
  "puzzle",
  "quasar",
  "rainbow",
  "sunflower",
  "turtle",
  "unicorn",
  "vortex",
  "whisper",
  "xylophone",
  "yacht",
  "zebra",
  "avocado",
  "biscuit",
  "cactus",
  "dolphin",
  "firefly",
  "galaxy",
  "harmony",
  "iceberg",
  "jackal",
  "kiwifruit",
  "marsh",
  "nectar",
  "ocean",
  "peacock",
  "quilt",
  "sapphire",
  "tornado",
  "umbrella",
  "violet",
  "walrus",
  "cinnamon",
  "dandelion",
  "emerald",
  "flamingo",
  "gardenia",
  "honeydew",
  "inkling",
  "koala",
  "lavender",
  "mosaic",
  "ninja",
  "opal",
  "pebble",
  "quokka",
  "raspberry",
  "snowflake",
  "teacup",
  "ukulele",
  "vanilla",
  "whistle",
  "yarn",
  "zucchini",
  "beetle",
  "cylinder",
  "dolphin",
  "fireball",
  "giraffe",
  "hedgehog",
  "jovial",
  "kettle",
  "lemonade",
  "marigold",
  "nectarine",
  "octagonal",
  "piranha",
  "quokka",
  "rocket",
  "starfish",
  "telescope",
  "umbrella",
  "violet",
  "wombat",
  "xenon",
  "yonder",
];
const ruWords = [
  "мир",
  "день",
  "дом",
  "кот",
  "лес",
  "мост",
  "вода",
  "луна",
  "друг",
  "зима",
  "снег",
  "свет",
  "путь",
  "солнце",
  "лето",
  "глаз",
  "мама",
  "отец",
  "рыба",
  "ночь",
  "дождь",
  "трава",
  "звезда",
  "ветер",
  "лист",
  "огонь",
  "цветок",
  "птица",
  "город",
  "река",
  "стул",
  "стол",
  "машина",
  "небо",
  "окно",
  "дерево",
  "книга",
  "человек",
  "рука",
  "яблоко",
  "камень",
  "земля",
  "собака",
  "кошка",
  "волк",
  "часы",
  "карандаш",
  "ручка",
  "дорога",
  "корабль",
  "поезд",
  "солнце",
  "море",
  "школа",
  "учитель",
  "буква",
  "язык",
  "шар",
  "конь",
  "снегирь",
  "бабушка",
  "дедушка",
  "подруга",
  "герой",
  "парк",
  "работа",
  "кофе",
  "чай",
  "сок",
  "морковь",
  "сало",
  "сыр",
  "хлеб",
  "пирог",
  "молоко",
  "перо",
  "крыло",
  "паук",
  "сказка",
  "ключ",
  "дверь",
  "пол",
  "сапог",
  "портфель",
  "кровать",
  "диван",
  "телефон",
  "интернет",
  "письмо",
  "замок",
  "замок",
  "картина",
  "музей",
  "театр",
  "песня",
  "танец",
  "игра",
  "подарок",
  "мечта",
];
const itWords = [
  "casa",
  "gatto",
  "cane",
  "sole",
  "luna",
  "stella",
  "mare",
  "montagna",
  "fiume",
  "albero",
  "fiore",
  "giardino",
  "libro",
  "penna",
  "matita",
  "scuola",
  "maestro",
  "amico",
  "amica",
  "cielo",
  "notte",
  "giorno",
  "strada",
  "auto",
  "treno",
  "aereo",
  "bicicletta",
  "porta",
  "finestra",
  "letto",
  "sedia",
  "tavolo",
  "cibo",
  "acqua",
  "pane",
  "latte",
  "formaggio",
  "pizza",
  "pasta",
  "riso",
  "frutta",
  "mela",
  "pera",
  "uva",
  "arancia",
  "limone",
  "pesca",
  "fragola",
  "banana",
  "pomodoro",
  "città",
  "paese",
  "villaggio",
  "montagna",
  "bosco",
  "lago",
  "vento",
  "pioggia",
  "neve",
  "fuoco",
  "chiave",
  "telefono",
  "computer",
  "lettera",
  "amore",
  "cuore",
  "famiglia",
  "nonno",
  "nonna",
  "madre",
  "padre",
  "fratello",
  "sorella",
  "bambino",
  "bambina",
  "uomo",
  "donna",
  "giovane",
  "vecchio",
  "gente",
  "lavoro",
  "vacanza",
  "soldi",
  "tempo",
  "caldo",
  "freddo",
  "estate",
  "inverno",
  "primavera",
  "autunno",
  "musica",
  "canzone",
  "danza",
  "film",
  "teatro",
  "arte",
  "quadro",
  "museo",
  "regalo",
  "sogno",
];
export const LANGUAGES = {
  en: {
    src: "images/uk.svg",
    start: "Start game",
    logo: "[ HANGMAN GAME ]",
    confirm: "Are you sure you want to quit and lose your progress",
    tries: "TRIES LEFT: ",
    quit: "Quit",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    mode: "Dark mode",
    again: "Play again",
    win: "You won",
    lose: "You lost",
    was: "The word was",
    words: enWords,
  },
  ru: {
    src: "images/ru.svg",
    start: "Начать игру",
    logo: "[ ВИСЕЛИЦА ]",
    confirm: "Вы уверены, что хотите закончить игру и потерять прогресс?",
    tries: "ОСТАЛОСЬ ПОПЫТОК: ",
    quit: "Выйти",
    alphabet: "АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ",
    mode: "Тёмная тема",
    again: "Играть снова",
    win: "Вы выиграли",
    lose: "Вы проиграли",
    was: "Было загадано слово",
    words: ruWords,
  },
  it: {
    src: "images/it.svg",
    start: "Avvia il gioco",
    logo: "GIOCO DELL'IMPICCATO",
    confirm: "Sei sicuro di voler uscire e perdere i tuoi progressi?",
    tries: "TENTATIVI RIMASTI: ",
    quit: "Esci",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    mode: "Modalità scura",
    again: "Gioca di nuovo",
    win: "Hai vinto",
    lose: "Hai perso",
    was: "È stata indovinata la parola",
    words: itWords,
  },
};

export const WORDS = () => {
  let currentLanguage = localStorage.getItem("language");
  return LANGUAGES[currentLanguage].words;
};
export const KEYBOARD_LETTERS = () => {
  let currentLanguage = localStorage.getItem("language");
  return Array.from(LANGUAGES[currentLanguage].alphabet);
};
